name: wes_germline_variant_calling
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - bwa
  - samtools
  - gatk4
  - picard
  - fastqc
  - multiqc
  - bcftools
  - seqtk
  - snpeff
  - tabix
  - wget
